#ifndef dictu_ast_event_h
#define dictu_ast_event_h

typedef enum {
    AST_DECLARE_CONST,
    AST_DECLARE_VAR,
    AST_DECLARE_FUNCTION,
    AST_DECLARE_ARROW_FUNCTION,
    AST_DECLARE_CLASS,
    AST_DECLARE_TRAIT,
    AST_DECLARE_CLASS_ABSTRACT,
    AST_DECLARE_FUNCTION_PARAM,
    AST_NAME,
    AST_SET,
    AST_RETURN,
    AST_DECLARE_ENUM,
    AST_ENUM_VALUE,
    AST_BLOCK,
    AST_BLOCK_END,
    AST_IMPORT,
    AST_END,
    AST_BRANCH,
    AST_FOR_LOOP,
    AST_WHILE_LOOP,
    AST_FUNCTION_CALL,
    AST_USE_STATEMENT,
    AST_INSTANCE,
    AST_SUBSCRIPT,
    AST_INDEX,
    AST_SUBSCRIPT_END,
    AST_INDEX_END,
} AstEventCode;

#endif